command xray:
	trigger:
		loop all blocks in radius 25 of player:
			if loop-block is stone, dirt, andesite, granite, gravel, diorite or infested stone:
				make player see loop-block as white stained glass 
command unxray:
	trigger:
		loop all blocks in radius 25 of player:
			if loop-block is stone, dirt, glass block, andesite, granite, gravel, diorite or infested stone:
				make player see loop-block as loop-block
