command /rules:
  trigger:
    create a gui with virtual chest inventory named "&e&l        SERVER RULES":
      format gui slot 10 with light green dye named "&2&lMinor Infractions" with lore "&a ✖ Overuse of Caps" and " &2✖ Spam of any kind" and " &a✖ Excessive Spam" and " &2✖ Agressive Player Disrespect" and " &a✖ Staff Disrespect" and " &2✖ Promoting Spam" and " &a✖ Impersonating Staff" and " &2✖ Discussing Servers" 
      format gui slot 13 with yellow dye named "&6&lModerate Infractions" with lore "&e ✖ Toxicity" and " &6✖ Advertising Links" and " &e✖ Boosting Players" and " &6✖ Mute Evading" and " &e✖ Hate Speech" and " &6✖ Scamming" 
      format gui slot 16 with red dye named "&4&lSevere Infractions" with lore "&c ✖ 1 Auto Miner PER Island" and " &4✖ Hack / Macros / Modifcations" and " &c✖ Exploits / Glitches (Report)" and " &4✖ Advertising" and " &c✖ Ban Evading" and " &4✖ Releasing Personal Information" and " &c✖ Inappropriate IGNs / Skins" and " &4✖ DDoS / DOX / SWAT Threats" and " &c✖ Death Threats / Wishes" and " &4✖ Encouraging Suicide" and " &c✖ Racial / Homophobic Slurs" and " &4✖ Griefing / Stealing" 
      format gui slot 0, 1, 2, 9, 11, 18, 19, and 20 with green stained glass pane named "&2" 
      format gui slot 3, 4, 5, 12, 14, 21, 22, and 23 with yellow stained glass pane named "&2" 
      format gui slot 6, 7, 8, 15, 17, 24, 25, and 26 with red stained glass pane named "&2" 
    open gui last gui to player