on off hand switch:
	cancel event
	make player execute command "/is menu"

on swap hand items:
	cancel event

on inventory click:
	inventory type is player inventory
	cursor slot of player is item:  
		index of event-slot is 40
		slot 40 of player's inventory is item
		cancel event

#command talonisgay:
#	trigger:
#		create a gui with id "%player%" with virtual chest inventory with 3 rows named "Talon is a hoe":
#			make gui slot 0 with diamond named "Talon is poor":
#				if clicked type is middle mouse button:
#					edit gui with id "%player%":
#						make gui slot 0 with dirt named "Talon is mega small pp"
#		open gui last gui to PLAYER
